### ISSUE TITLE
Plugin causing Dataview Tasks metadata to render as a Key:Value List

### ISSUE THREAD

**Issue by dahliyah** [christianwannerstedt/obsidian-key-value-list#14]
With the plugin enabled: checklist with Dataview Task metadata:

![image](https://github.com/christianwannerstedt/obsidian-key-value-list/assets/105956987/2d83d14d-b93b-4c3d-a58f-adb123fa1827)

With the plugin disabled:
![image](https://github.com/christianwannerstedt/obsidian-key-value-list/assets/105956987/d30be2d4-643d-49c5-bc29-e9c02c9b4cb3)

Although it looks pretty neat I'd prefer it to not do this lol
Great plugin so far and thank you very much for fixing the last issue I brought up.

**Comment by christianwannerstedt** [comment]
Hey! This functionality might have been touched in the latest release ([1.5.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.5.0)) since that will handle the double delimiters (::) a bit better. I'm not sure how it will affect the icon rendered by the other plugin tho. In my local setup with the dataview plugin the metadata renders fine, but I don't see that calendar icon..
Plz let me know if this fixes your issue.

**Comment by christianwannerstedt** [comment]
I'm closing this issue since I believe it's fixed
