### ISSUE TITLE
Compatibility with Dataview?

### ISSUE THREAD

**Issue by jayambede** [christianwannerstedt/obsidian-key-value-list#2]
Looks like a nice addition to Obsidian. But just for my understanding: 

Is this, and if, in which way compatible with Dataview ?
Can, and how do I use it with e.g. dataview queries?
And how does it relate to the Obsidian Properties function?

Thanks for your effort!

**Comment by christianwannerstedt** [comment]
Hey! Sorry for the late reply..
The main idea with this plugin is just to provide some additional styling to certain lists, so it doesn't come with any additional logic or integrations with e.g. Dataview, but rather only provides pure formatting.

It would ofc be possible to turn these key-value lists into something more, with extended functionality, but that's not in the scope of this plugin, since I want it to be super slim and easy to use.

When it comes to the Obsidian properties, I might add some additional logic to customise lists in a specific document through these, so that it would be possible to disable the plugin or change individual settings on a document basis.
